name: Java CI with Maven

on:
# Configure trigger for action
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
      # Java version must match .pom file
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots verify
        mvn --batch-mode -B package --file pom.xml

  package:
    name: Package Build Data as Artifact
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
